export * from './landing-page/landing-page.component';
export * from './home/home.component';
export * from './proyecto-equipo/proyecto-equipo.component';
export * from './proyecto-plataforma/proyecto-plataforma.component';
export * from './evaluaciones-madurez/evaluaciones-madurez.component';
export * from './evaluaciones-proveedor/evaluaciones-proveedor.component';
export * from './evaluaciones-startup/evaluaciones-startup.component';
export * from './podcasts/podcasts.component';
export * from './informe/informe.component';
